### ISSUE TITLE
Issue when running sudo apt-get update && sudo apt-get install mongodb-org -y

### ISSUE THREAD

**Issue by nathan-a-macleod** [jacob-macleod/Chirpr-Social-Network#1]
One of the instructions in the DOCKERFILE is: 
`sudo apt-get update && sudo apt-get install mongodb-org -y`

However when I run the command, the next command doesn't work - so there is an error. Here is the error message I get when running `sudo apt-get update && sudo apt-get install mongodb-org -y`:

```
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Ign:2 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 InRelease                                                            
Hit:3 https://deb.debian.org/debian buster InRelease                                                                                 
Get:4 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 Release [1,488 B]
Hit:5 https://deb.debian.org/debian-security buster/updates InRelease
Ign:6 https://storage.googleapis.com/cros-packages/88 buster InRelease
Hit:7 https://storage.googleapis.com/cros-packages/88 buster Release
Get:8 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 Release.gpg [801 B]
Ign:8 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 Release.gpg
Reading package lists... Done
W: GPG error: http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 656408E390CFB1F5
E: The repository 'http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by jacob-macleod** [comment]
Thanks for opening this issue Nathan, I'll check it out when I can

**Comment by jacob-macleod** [comment]
I think the issue was due to the fact that you need to import a key for the repository since one is not publicly avaliable. To import the key, please can you try to enter:
`wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -`
It should respond with `OK`. If it doesn't and if it displays an error message saying gnupg is not installed, please could you run the following commands: 

`sudo apt-get install gnupg`

`wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -`

Next, you can run the commands in the DOCKERFILE.

Please let me know if it works of if there's any errors!

Also, I'm not sure why the install ran without any errors on my computer, although I may have installed an apt package a while ago that allowed installing of repositories with no key... I can't remember though!

**Comment by nathan-a-macleod** [comment]
Thanks that works :)

**Comment by jacob-macleod** [comment]
Great, I'll close the issue!
